name: Node.js Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Save SSH key to file
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key

    - name: Deploy to server
      run: |
        ssh -i ubuntu@47.128.214.124 "C:\\Users\\vanth\\keys\\Lightsail.pem" 'cd node-app && git pull origin main && npm install && pm2 restart app'
