name: Node.js Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to server
      run: |
        sh ubuntu@47.128.214.124 'cd /node-app && git pull origin main && npm install && pm2 restart app'
