name: Docker Image CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create env file
      run: echo "${{ secrets.AUTH_ENV }}" > .env

    - name: Build the Docker image
      run: docker build --progress=plain -t vanthuy/nodejs_auth .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push vanthuy/nodejs_auth

    - name: SSH into deployment server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DELOY_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          docker pull vanthuy/nodejs_auth
          docker stop nodejs_auth_container || true
          docker rm nodejs_auth_container || true
          docker-compose -f /node-app/docker-compose.yml up -d
